#!/bin/bash
################################################################################
# Git Hooks Installation Script
# Purpose: Install post-commit hook to auto-sync AI chats
# Usage: ./install-git-hooks.sh [project-path]
################################################################################

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

PROJECT_DIR="${1:-$(pwd)}"

# Validate project directory
if [ ! -d "${PROJECT_DIR}/.git" ]; then
    log_error "Not a git repository: ${PROJECT_DIR}"
    exit 1
fi

log_info "Installing git hooks for: ${PROJECT_DIR}"

# Get the absolute path to sync-chats.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC_SCRIPT="${SCRIPT_DIR}/sync-chats.sh"

if [ ! -f "${SYNC_SCRIPT}" ]; then
    log_error "sync-chats.sh not found at: ${SYNC_SCRIPT}"
    exit 1
fi

# Create post-commit hook
HOOK_FILE="${PROJECT_DIR}/.git/hooks/post-commit"

log_info "Creating post-commit hook..."

cat > "${HOOK_FILE}" <<EOF
#!/bin/bash
################################################################################
# Post-commit hook - Auto-sync AI chat history
# Generated by install-git-hooks.sh
################################################################################

# Run chat sync script
"${SYNC_SCRIPT}" "${PROJECT_DIR}" || true

exit 0
EOF

chmod +x "${HOOK_FILE}"

log_info "✓ Post-commit hook installed"

# Create .gitignore entries for chat directories
GITIGNORE="${PROJECT_DIR}/.gitignore"

log_info "Updating .gitignore..."

# Check if entries already exist
if [ -f "${GITIGNORE}" ]; then
    if ! grep -q "^\.claude-chats/" "${GITIGNORE}" 2>/dev/null; then
        echo "" >> "${GITIGNORE}"
        echo "# AI Chat History (synced automatically)" >> "${GITIGNORE}"
        echo "# Uncomment to exclude from git:" >> "${GITIGNORE}"
        echo "# .claude-chats/" >> "${GITIGNORE}"
        echo "# .bob-chats/" >> "${GITIGNORE}"
        log_info "✓ Added chat directories to .gitignore (commented out)"
    else
        log_info "✓ .gitignore already contains chat directory entries"
    fi
else
    cat > "${GITIGNORE}" <<EOF
# AI Chat History (synced automatically)
# Uncomment to exclude from git:
# .claude-chats/
# .bob-chats/
EOF
    log_info "✓ Created .gitignore with chat directory entries"
fi

log_info "============================================"
log_info "Git Hooks Installation Complete!"
log_info "============================================"
log_info "Post-commit hook: ${HOOK_FILE}"
log_info ""
log_info "How it works:"
log_info "1. Every time you commit, the hook runs automatically"
log_info "2. It syncs Claude Code and IBM Bob chats to:"
log_info "   - .claude-chats/"
log_info "   - .bob-chats/"
log_info "3. Changes are committed and pushed automatically"
log_info ""
log_info "Manual sync: ${SYNC_SCRIPT}"
log_info ""
log_info "To disable auto-sync:"
log_info "  rm ${HOOK_FILE}"
log_info ""
log_info "To exclude chats from git:"
log_info "  Uncomment the lines in .gitignore"
log_info "============================================"

# Made with Bob
